# Generated by Django 5.2 on 2025-05-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_active_publication",
            field=models.BooleanField(default=True, verbose_name="Признак публикации"),
        ),
    ]
