# Generated by Django 5.2 on 2025-05-31 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_options_product_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Введите цену продукта.",
                max_digits=10,
                verbose_name="Цена",
            ),
        ),
    ]
