# Generated by Django 5.2 on 2025-06-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите изображение категории.",
                null=True,
                upload_to="images/",
                verbose_name="Изображение",
            ),
        ),
    ]
